# Generated by Django 2.1 on 2018-08-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField()),
                ('project_text', models.TextField()),
                ('project_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
