# Generated by Django 2.1 on 2018-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_project_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_extra',
            field=models.TextField(default=' '),
        ),
    ]
